[package]
name = "v-collections"
version = "0.1.0"
edition = "2021"
description = "A collection of rust datastructures written for fun without profit."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
